### ISSUE TITLE
PDF downloaded with zotra is damaged

### ISSUE THREAD

**Issue by Vidianos-Giannitsis** [mpedramfar/zotra#6]
Hello,

I am trying to download pdfs from ScienceDirect using Zotra (specifically testing with [this](https://www.sciencedirect.com/science/article/pii/S0960852419311587?via%3Dihub)). The entry is correctly added to my bib file, however, the pdf that is downloaded is not correct. When trying to open it, I get: 

File mode specification error: (error epdfinfo: Error opening /home/vidianos/Sync/Zotero_pdfs/test.pdf:PDF document is damaged)

I have access to the pdf and when trying to add it with Zotero it does work. Do you have any idea why the downloaded pdf is not correct? I really would like this to work, it would be a pleasure to not need to open Zotero and work with it through Emacs.

Thanks!

**Comment by mpedramfar** [comment]
Hi,

It seems to need access through the institution in order to get the pdf. I guess Zotero gets it because it has a browser extension and therefore knows about the cookies and basically has the same access as you. Zotra doesn't know about that.
There might be a way to get the cookies from the browser so that Zotra can download the pdfs directly, but that doesn't seem very secure to me.
An alternative could be to open the links in the browser, instead of attempting to download it directly. But I'm not sure how that can be detected automatically. This sounds like an addition to the Zotero translation server.

I could add a function that opens the attachment in the browser, so that the user can choose to do that instead of trying to download it through Emacs. Though I'm not sure how useful that would be. Currently you can just open the link using citar or helm-bibtex and then click on the attachment.

**Comment by mpedramfar** [comment]
In the link you sent, it downloads a html file instead of a pdf. Now I've added a function that checks the downloaded file to see if its file extension matches its mime type. If they don't match (e.g. we have an html file named paper.pdf), then it just deletes the downloaded file and opens the attachment in the browser.

**Comment by Vidianos-Giannitsis** [comment]
Yeah, that's a good point. I forgot that this is independent of the browser and therefore doesn't know that I have access to it. After playing around with this a bit, I think I have come to the minimum requirement I would want from this. I am pretty sure it can be implemented fairly easily.

Download the pdf, pass it to Emacs and then run a function that moves it to `zotra-download-attachment-default-directory` and renames it as citekey.pdf. Seeing as we can collect the bib file, it shouldn't (I think at least) be hard to have a function collecting the citekey and renaming the pdf to citekey.pdf. Even though with this method the bib entry never gets a file field, if the pdf is in the directory bibtex expects it to be and it has the name citekey.pdf, it can identify it so the rest of my workflow works correctly.

The most interesting part of this is how do we pass the pdf to Emacs. For starters, this can probably be done manually by inputing the file name in something like `find-file` and then when the pdf is selected, do the aforementioned tasks. That's probably as automated as it gets, which is definitely inferior to Zotero's click one button and the rest is automatically there. However if all that needs to be done is copy the url and download the pdf and the rest is done automatically, its value is close to that of Zotero. And the fact that it is inside Emacs and I don't even need Zotero open makes it a bit extra cool so I would try it.

What do you think about this? Does it sound like a reasonable addition?

**Comment by mpedramfar** [comment]
Are you using bibtex-completion? In helm-bibtex, you can do this using "Add PDF to library" function. First you download the file. Then go to the citation, press `C-c C-o` on the citekey, choose "Add PDF to library", then "[f]ile", then select the downloaded file and it'll do the rest.

**Comment by Vidianos-Giannitsis** [comment]
I am indeed using bibtex-completion and that is a feature I didn't even know existed, thanks! Well, tbh it doesn't surprise me that I didn't know it. There is so much of Emacs that I just don't know, even though I consider myself an Emacs power user. I will be trying this workflow out tomorrow, but seeing as it will probably work, i am closing this issue from now.

Will remessage you if I have any more questions. Thanks again for the great work you have done here.
